### ISSUE TITLE
Configure Redirect for Existing Documize Instance

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/platform-services-documize#5]
### Story

As a user of documize, I'd like to automatically be redirected to the new documize instance when it is live in production on the Silver Cluster.

### Definition of Done

- [x] Redirect Configured and Tested with Test Environment in Pathfinder and Silver Clusters
- [x] Manifests for Redirect Setup in Repository and Ready to be enabled

**Comment by j-pye** [comment]
@sbathgate @yhfreeman What's the status on this ?

**Comment by yhfreeman** [comment]
Still in progress. The manifests for redirect setup are developed. The next step is to configure and test the direct in dev environment. cc @sbathgate
