### ISSUE TITLE
Setup Database Backups

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/platform-services-documize#9]
### Story

As an Ops persoon, I would like the Documize database to be backed up regularly so that it can be restored in the event of database failure or some other catastrophic event.

### Definition of Done

- [x] Backups Configured for Prod Env
- [x] Manifests for Backup Automation Committed and Reviewed
- [x] Restore Process Tested and Verified

**Comment by yhfreeman** [comment]
PR #13 relates to this ticket.
